### ISSUE TITLE
[feat/solana-nft] NFT buy/sell using Tensor

### ISSUE THREAD

**Issue by TropicalDog17** [supervelo/velopay#10]
# Overview
Using Tensor API for buying NFT from Tensor Marketplace

# Feature

- [ ] Buying the lowest listing NFT from a particular collection(e.g: I want to buy a Drip Nation NFT on Tensor using my available balance) 
- [ ] Buying limit orders(e.g: Can you purchase me 1 Okay Bears NFT for 10 SOL ?.)
- [ ] Buying a set of NFT in bulk when they satisfy specific criteria.
# Resources: 

https://tensor-hq.notion.site/PUBLIC-Tensor-Trade-API-Docs-alpha-b18e1a196187473bac9b5d6de5b47032

note for @batm9n: Could you please confirm if I am heading in the right track? Because it seems that in order to construct a buy tx from user intent, we need to somehow retrieve the onchainId of the NFT, the marketplace name(e.g: Tensor). But copy the id seem unintuitive, and I think it is more feasible to choose NFT for user based on some criteria(for now I think lowest price is easy to implement)

**Comment by MrSufferer** [comment]
@TropicalDog17 
Yes, it sounds like you're in the right direction with your NFT buy/sell feature request. 
Also, I want to ask if you could implement buying 1 or multiple NFTs when the floor price meets the specific condition(like limit orders).

Now, let's consider the three cases of NFT buyers:
1. The Newbie: These users are drawn to famous NFT collections but may also want to choose specific NFTs that represent themselves. They often buy it manually because famous NFT collections are not cheap.

2. Traders: This group is looking for opportunities in the market, often waiting for price dips or sniping newly listed collections. Then they do bull-purchases at floor price.

3. Copy-Traders: These users are newbies interested in profit. They follow profitable wallets and buy multiple NFTs (or only 1 nft) similar to those wallets. 

Since retrieving NFT IDs can be challenging, focusing on case 2 (traders) is a practical & easiest approach. Let me hear your thoughts!

**Comment by TropicalDog17** [comment]
``` json
 {
          "id": "986f1f60-7227-4b91-a476-78177c38595a",
          "slug": "986f1f60-7227-4b91-a476-78177c38595a",
          "slugMe": "bonkz",
          "slugDisplay": "bonkz",
          "statsOverall": {
            "floor1h": 0.00007093204709884837,
            "floor24h": -0.00007092198581559739,
            "floor7d": -0.04348710990502036,
            "floorPrice": "14.1",
            "numListed": 702,
            "numMints": 15000,
            "priceUnit": "Sol",
            "sales1h": 8,
            "sales24h": 363,
            "sales7d": 4287,
            "volume1h": "111.420555484",
            "volume24h": "5148.05422215",
            "volume7d": "65421.229946127"
          },
          "statsSwap": {
            "buyNowPrice": "14.1",
            "sellNowPrice": "13.34739229"
          },
          "statsTSwap": {
            "buyNowPrice": "14.1",
            "nftsForSale": 68,
            "numMints": 15000,
            "priceUnit": "Sol",
            "sales7d": 165,
            "sellNowPrice": "13.34739229",
            "solDeposited": "333.577666552",
            "volume7d": "2510.812407089"
          },
          "statsHSwap": {
            "buyNowPrice": "14.111",
            "nftsForSale": 111,
            "priceUnit": "Sol",
            "sales7d": 538,
            "sellNowPrice": "13.192",
            "solDeposited": "107.407306455",
            "volume7d": "7937.655651294"
          },
          "tswapTVL": "1304.773182552",
          "firstListDate": 1673378928000,
          "name": "BONKz"
        },
```
@batm9n This is the sample data retrieved from the API, What criteria do you think is useful to decide whether to make a purchase or not? I can try to implement it today, looking forward hearing your suggestion.

API doc: .https://tensor-hq.notion.site/PUBLIC-Tensor-Trade-API-Docs-alpha-b18e1a196187473bac9b5d6de5b47032#56b333bfe0b641f8acad51a963a04f4f

**Comment by MrSufferer** [comment]
@TropicalDog17 
The floor price should be extracted from the user's query
(e.g. "Can you purchase me 1 Okay Bears NFT with Gold Chain Trait when the price goes under 10 SOL?").

You can use clockwork to schedule a Tensor transaction.

**Comment by MrSufferer** [comment]
@TropicalDog17 
It seems that Clockwork hasn't supported NFT price Oracle yet. You can read it [here](https://docs.clockwork.xyz/reference/threads/triggers).

For now, let's use Tensor's [Collection bid](https://tensor-hq.notion.site/PUBLIC-Tensor-Trade-API-Docs-alpha-b18e1a196187473bac9b5d6de5b47032#25fb500214ea4b7197166ae96539b07e) to execute buy limit orders.
Also, check if you could configure the API request with some [unexpected cases](https://docs.tensor.trade/trade/get-started-with-tensors-amm/purchase-caps).

Example prompt: "Can you purchase me 1 Okay Bears NFT for 10 SOL ?". 

Is this ok?

**Comment by TropicalDog17** [comment]
@batm9n I'm struggling to find a method for associating the name of an NFT collection with its corresponding identifier (slug).

My current approach is manually entering this information into a constant.js file, where "OkayBear" is considered a collection, not an individual NFT. This brings me back to my initial question: **How do we determine the exact NFT we want to buy?**

**Comment by MrSufferer** [comment]
@TropicalDog17 
We may use Tensor API to retrieve a list of collections that have similar names to our request.
If they didn't support it yet, then we need to configure our own constants.

For the exact NFT, we can't determine it without the id. So, just buy the lowest-price NFT.

If the users provide further contexts like "under 10 SOL" or "Wearing a gold chain" then you should place a bid for them with the lowest-price NFT at the time they request.

**Comment by MrSufferer** [comment]
Closing in favour of #11
