### ISSUE TITLE
[feat/DCA-strategy] DCA via Raydium/Openbook

### ISSUE THREAD

**Issue by TropicalDog17** [supervelo/velopay#12]
Tasks

- [ ] 

- [ ] 

- [ ]

**Comment by MrSufferer** [comment]
Not prioritized.

See the fast method [here](https://station.jup.ag/docs/dca/integration).

**Comment by batm9n** [comment]
closed in favor of #21

**Comment by MrSufferer** [comment]
closed in favor of #21
