### ISSUE TITLE
Refactor(prompt): Better web3 assistant

### ISSUE THREAD

**Issue by MrSufferer** [supervelo/velopay#18]
- [x] [Lite mode](https://github.com/supervelo/velopay/issues/18#issuecomment-1754199817)
- [x] Answer Unmatched Request (solana-validator embedding trained data => need to replace)
- [x] GPT QA UI

**Comment by MrSufferer** [comment]
Should follow the mission: monetary automation & stable income.

Note: Sometimes I will use "programmable money" instead of "monetary automation". It's just a higher form of automatic money.

**Comment by TropicalDog17** [comment]
@batm9n As I proposed earlier, a "Lite" mode, where the "newbie" users can choose options and fill out pre-defined fields might be a good idea in case we can't deliver the text suggestion feature in time.

**Comment by MrSufferer** [comment]
> @batm9n As I proposed earlier, a "Lite" mode, where the "newbie" users can choose options and fill out pre-defined fields might be a good idea in case we can't deliver the text suggestion feature in time.

Added to the list!

**Comment by MrSufferer** [comment]
@PhamQuangNhut Can you get the Solana ChatGPT vectorstores for me?
